#!/bin/sh

die() {
    echo $*
    exit 1
}

git commit -a -m 'auto commit' || die commit failed
REV=$(date +%s)
VER=0.0.1+git$REV
export DEBEMAIL='Alexey Alexandrov <swined@gmail.com>'
dch -v $VER "$REV" || die dch failed
git commit -a -m 'auto commit' || die commit failed
git-buildpackage -rfakeroot -us -uc -b || die build failed
rm ../lj2rss_${VER}_i386.changes
#for deb in ../*.deb; do sudo reprepro -b /var/web/deb.swined.net includedeb unstable $deb && rm $deb || die failed to add deb to repository; done
#sudo apt-get update
#sudo apt-get install -y --force-yes lj2rss
